### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by nathansamson** [openscript/awesome_hstore_translate#7]
Does the system allow for easy ordering?

eg. order(name: :asc) where name is a translated field? How well does it combine with fallbacks?

I did not see anything in the documentation, nor did I see anything in the code that would support this on first sight

Would it be hard to implement?

**Comment by openscript** [comment]
Thank you for creating the issue.

Ordering is not implemented, but it shouldn't be hard to do so. I'll have a look into it this weekend.

**Comment by openscript** [comment]
I've implemented sorting. Please check it out.

**Comment by nathansamson** [comment]
Hi,

Thanks for sorting this out (pun not intended).

Note that I have rolled out our own implementation based on JSON(B) which also implements fallbacks in sorting.

**Comment by daniel-rikowski** [comment]
The 0.3 release breaks `order` calls without a sorting direction. e.g. `order(:position)`:
> NoMethodError: private method `select' called for :position:Symbol

**Comment by openscript** [comment]
@daniel-rikowski I'll fix that in a second.

**Comment by openscript** [comment]
Sorry about that.

**Comment by openscript** [comment]
@daniel-rikowski I've pushed another version. 

Probably I'll also switch over to a json solution, due it's more handy if you need to deliver json through a api anyway.

**Comment by daniel-rikowski** [comment]
Thank you!

Symbols do work now, but combinations still do not, e.g.

```
Model.order(:position, id: :desc)
```

This results in a call like `order(position: :asc, { id: :desc } => :asc }`

**Comment by openscript** [comment]
@daniel-rikowski I'll look into it.

**Comment by openscript** [comment]
This Project accepts [Octotreats](https://octotreat.com). You may promise the owner a treat upon completion of this Issue [here](https://octotreat.com/projects/7/treats/new?issue_id=31)
